opcua:
  client:
    name: "NavServer"
  server:
    address: 0.0.0.0
    port: 12686
  application:
    name: My App
    uri: "urn:cz:cvut:ciirc:simulation:opcserver"
    namespace:
      uri: "${opcua.application.uri}:namespace"

rabbit:
  queue:
    name: "NavserverOpc"
  receiver:
    queue:
      name: "Navserver"

spring:
  rabbitmq:
    host: "localhost"